export const GET_BLOCKS = 'GET_BLOCKS';
export const GET_BLOCKS_FAILED = 'GET_BLOCKS_FAILED';
export const GET_BLOCKS_SUCCESS = 'GET_BLOCKS_SUCCESS';

export const FETCH_BLOCK = 'FETCH_BLOCK';
export const FETCH_BLOCK_FAILED = 'FETCH_BLOCK_FAILED';
export const FETCH_BLOCK_SUCCESS = 'FETCH_BLOCK_SUCCESS';

export const FETCH_TRANSACTION = 'FETCH_TRANSACTION';
export const FETCH_TRANSACTION_FAILED = 'FETCH_TRANSACTION_FAILED';
export const FETCH_TRANSACTION_SUCCESS = 'FETCH_TRANSACTION_SUCCESS';

export const FETCH_ADDRESS = 'FETCH_ADDRESS';
export const FETCH_ADDRESS_FAILED = 'FETCH_ADDRESS_FAILED';
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS';